### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [geonetwork/docker-geonetwork#5]
I was build this image on arm64 architecture and build successed .So I want to know we can add it to the https://hub.docker.com/u/arm64v8/ ?

**Comment by doublebyte1** [comment]
That would be great

**Comment by longquan7** [comment]
@doublebyte1 If yes, are there any proposals for submission?

**Comment by tianon** [comment]
Since `geonetwork` is `FROM tomcat:...`, this `Dockerfile` _should_ just work as-is with any the architectures supported by `tomcat` (https://github.com/docker-library/official-images/blob/83445dba81738f34d37e13fa811b34841d1d6def/library/tomcat#L38, `amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x`).

See https://github.com/docker-library/official-images#architectures-other-than-amd64 and https://github.com/docker-library/official-images#multiple-architectures for more information about multi-architecture official images. :+1:

**Comment by doublebyte1** [comment]
@tianon in theory this should work out-of-the-box, but please let me know if you (or anyone else) encounter(s) any issues when _running_ geonetwork

**Comment by longquan7** [comment]
@doublebyte1 If can be support can you add it to https://hub.docker.com/u/arm64v8/  ? thanks

**Comment by pmauduit** [comment]
There might be some runtime issues with x86-based setups, because of the limitations (4GB) on the addressable memory (already encountered on windows with a x86 JVM with a default GN webapp)

**Comment by lag-linaro** [comment]
@doublebyte1, we have tested this project on ARM64v8 and it does indeed just work.

I'd be happy to submit a pull request enabling it for ARM64v8 with your support.

**Comment by odidev** [comment]
Just to add...
Even I confirmed the working of ```geonetwork``` on ```arm64v8``` architecture.

If you guys agree then a **PR** can be raised to ```library/geonetwork``` to add ```arm64v8``` officially.

**Comment by odidev** [comment]
Raised a [PR](https://github.com/docker-library/official-images/pull/4680) based on comments from @tianon.

**Comment by doublebyte1** [comment]
@odidev just out of curiosity: in which sort of device did you try running geonetwork? on a Raspberry PI?

**Comment by odidev** [comment]
Hi @doublebyte1,
I actually have ```Softiron-OD1000``` board with me which has ```arm64v8``` architecture.

**Comment by juanluisrp** [comment]
Support for multiple architectures has been finally added in https://github.com/docker-library/official-images/pull/4724

* `amd64`
* `arm32v5` 
* `arm32v7`
* `arm64v8`
* `i386`
* `ppc64le`
* `s390x`
